### ISSUE TITLE
InvalidOperationException: HttpContext is required. in pagination service constructor.

### ISSUE THREAD

**Issue by ugumerie** [mrahhal/MR.AspNetCore.Pagination#9]
Hello,

Is there any way one can make injection of the `IHttpContextAccessor` into PaginationService optional when using outside of httpcontext.

For example, I'm using masstransit to publish integration events to rabbitmq, on getting to one of the consumers or receive endpoints, that called a method using `IPaginationService`, it tried constructing the `IPaginationService` and threw `InvalidOperationException`, "HttpContext is Required". I feel because it is outside the scope of httpcontext. Though I want create my own implementation using just the first overload with `KeysetQueryModel` object without injecting `IHttpContextAccessor`.

Regards

**Comment by mrahhal** [comment]
Hello,

That makes sense. Should move the exception throwing from the ctor to only the places that actually need `HttpContext`.

**Comment by Ngreene-mwks** [comment]
Having the same issue.
I would push up a fix, but seem unable to.
Can we get a resolution on this please?

**Comment by mrahhal** [comment]
Will be released soon.

**Comment by mrahhal** [comment]
Released in v3.0.0.

**Comment by Ngreene-mwks** [comment]
Thanks!
